language: ruby
rvm:
- 2.1.0
cache: bundler
script:
- bundle install
- bundle exec rspec spec
- bundle exec rake build
- bundle exec middleman build --clean
deploy:
  provider: script
  skip_cleanup: true
  script: bash -c './deploy.sh'
  on:
    branch: master
