language: ruby
rvm:
- 2.1.0
cache: bundler
script:
- bundle exec rspec spec
- bundle exec rake build
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_9d680ccc9428_key -iv $encrypted_9d680ccc9428_iv
  -in .ssh/id_rsa.enc -out .ssh/id_rsa -d
